site_name: Coiote IoT Device Management platform
site_link: https://eu.iot.avsystem.cloud
short_name: Coiote IoT DM
coaps: coaps://eu.iot.avsystem.cloud:5684
freertos_files:
  0. Go to [Anjay-freertos-client](https://github.com/AVSystem/Anjay-freertos-client/releases/).
STM32L496G_BG96_binary:
  0. Download the `Anjay-freertos-client-STM32L496G-BG96.bin` file.
L462_binary:
  0. Download the `Anjay-freertos-client-B-L462E-CELL1-TYPE1SC.bin` file.
zephyr_files:
  0. Go to [Anjay-zephyr-client](https://github.com/AVSystem/Anjay-zephyr-client/releases).
nRF9160_binary:
  0. Download the `demo_nrf9160dk_merged.hex` file.
thingy91_binary:
  0. Download the `demo_thingy91_app_signed.hex` file.
