name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: npm install
      - run: npm install gulp-cli
      - run: gulp build 
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install ghp-import
      - run: mkdocs build
      - run: cp site/index.html site/docs_index.html
      - run: rm -f site/index.html
      - run: cp -R site dist
      - run: python ghpages.py
      #- run: mkdocs gh-deploy --force --clean --config-file ./mkdocs.yml
