name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: npm install
      - run: npm install gulp-cli
      - run: gulp build 
      - run: pip install -Iv mkdocs-material==6.2.6
      - run: pip install mkdocs-git-revision-date-localized-plugin
#      - run: docker run -v ${PWD}:/docs squidfunk/mkdocs-material:6.2.6 build 
      - run: pip install ghp-import
#      - run: mkdocs --version
      - run: pip install jinja2==3.0.0
      - run: mkdocs build
      - run: cp -R site dist/docs
      - run: python ghpages.py
      #- run: mkdocs gh-deploy --force --clean --config-file ./mkdocs.yml
